apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-ingress-controller
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
data:
  1883: {{ template "fullname-port" . }}